app1/urls.py
from django.urls import path
from .views import homepage, menu, chi_siamo, variabili, index

urlpatterns = [
    path('welcome/', homepage, name='home'),
    path('menu/', menu, name='menu'),
    path('chi_siamo/', chi_siamo, name='chi_siamo'),
    path('variabili/', variabili, name='variabili'),
    path('index/', index, name='index'),

]

libreria/urls.py
from django.urls import path
from .views import LibroListView,AutoreDetailViewCB,AutoreListView
app_name='libreria'

urlpatterns = [
    path('lista_libri', LibroListView.as_view(), name="lista_articoli"),
     path('autore/<int:pk>', AutoreDetailViewCB.as_view(), name="autore_detail"),
    path('lista_autori', AutoreListView.as_view(), name="lista_autori"),

]

progetto1/urls.py
from django.contrib import admin
from django.urls import path, include
from app1.views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',homepage,name='homepage'),
    path('app1/', include('app1.urls')),
    path('app2/', include('app2.urls')),
    path('news/', include('news.urls')),
    path('libreria/', include('libreria.urls')),
    path('form/', include('forms_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

libreria/models.py
from django.db import models


class Autore(models.Model):
    nome = models.CharField(max_length=20)
    nazione = models.CharField(max_length=20)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = "Autore"
        verbose_name_plural = "Autori"

class Genere(models.Model):
    genere = models.CharField(max_length=100)
    
    def __str__(self):
        return self.genere

    class Meta:
        verbose_name = "Genere"
        verbose_name_plural = "Generi"

class Libro(models.Model):
    titolo = models.CharField(max_length=100)
    autore = models.ForeignKey(
        Autore, on_delete=models.CASCADE, related_name="libri")
    genere = models.ForeignKey(
        Genere, on_delete=models.CASCADE, related_name="libri")
    isbn = models.CharField(max_length=20)

    def __str__(self):
        return self.titolo

    class Meta:
        verbose_name = "Libro"
        verbose_name_plural = "Libri"



# Create your models here.

libreria/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render,get_object_or_404
from .models import Genere, Libro, Autore
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

# Create your views here.

#Libri

class LibroListView(ListView):
    model=Libro
    template_name="lista_libri.html"

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        context["libri"]=Libro.objects.all()
        return context

#Giornalisti
def autoreDetailView(request, pk):
    autore=get_object_or_404(Autore, pk=pk)
    context={"autore":autore}
    return render(request, "autore_detail.html", context)

class AutoreDetailViewCB(DetailView):
    model=Autore
    template_name="autore_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['libri'] = context['autore'].libri.all()
        return context

class AutoreListView(ListView):
    model=Autore
    template_name="lista_autori.html"

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        context["autori"]=Autore.objects.all()
        return context

libreria/templates/autore_detail.html
{% extends 'base.html'%}
{%block title%}
{{autore.nome}}
{%endblock title%}

{%block content%}
<h1>{{autore.nome}}</h1>
<br>
<h3>Libri dell'Autore:</h3>
<br>
    {% for libro in libri %}
    <p><strong>Titolo: </strong>{{ libro.titolo }}</p>
    <p><strong>Autore: </strong>{{ libro.autore.nome }}</p>
    <p><strong>Genere: </strong>{{ libro.genere.genere }}</p>
    <p><strong>ISBN: </strong>{{ libro.isbn }}</p>
    <br>
    <br>
    
    {% endfor %}

    {%endblock content%}

libreria/templates/lista_autori.html
{% extends 'base.html'%}
{%block title%}
    Lista Autori
{%endblock title%}

{%block content%}
  <h4>Autori:</h4>
  <br>
  {% for autore in autori %}
    <p><strong>Autore {{ forloop.counter }}: </strong>{{ autore.nome }}</p>
    <p><strong>Nazione: </strong>{{ autore.nazione }}</p>
    <a class="btn btn-success" href="/libreria/autore/{{autore.id}}" role="button">Info autore</a>
    <br>
    <br>
    <br>
    <br>

  {% endfor %}

{%endblock content%}

libreria/templates/lista_libri.html
{% extends 'base.html'%}
{%block title%}
    Lista Libri
{%endblock title%}

{%block content%}
  <h4>Libri:</h4>
  <br>
  {% for libro in libri %}
    <p><strong>Titolo: </strong>{{ libro.titolo }}</p>
    <p><strong>Autore: </strong><a href="{% url 'libreria:autore_detail' pk=libro.autore.id %}">
      {{ libro.autore.nome }}
    </a></p>
    <p><strong>Genere: </strong>{{ libro.genere.genere }}</p>
    <p><strong>ISBN: </strong>{{ libro.isbn }}</p>
    <!-- <a class="btn btn-success" href="/libreria/autore/{{autore.id}}" role="button">Vai all'Autore</a> -->
    <br>
    <br>
    <br>
    <br>
  {% endfor %}

{%endblock content%}