app1/urls.py
from django.urls import path
from .views import homepage, menu, chi_siamo, variabili, index

urlpatterns = [
    path('welcome/', homepage, name='home'),
    path('menu/', menu, name='menu'),
    path('chi_siamo/', chi_siamo, name='chi_siamo'),
    path('variabili/', variabili, name='variabili'),
    path('index/', index, name='index'),

]

app2/urls.py
from django.urls import path
from .views import esempio_if, esempio_ifelse, esempio_elif, esempio_for
app_name = 'app2'
urlpatterns = [
    path('if/', esempio_if, name='if'),
    path('ifelse/', esempio_ifelse, name='else'),
    path('ifelif/', esempio_elif, name='elif'),
    path('for/', esempio_for, name='for'),
]

progetto1/urls.py
from django.contrib import admin
from django.urls import path, include
from app1.views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',homepage,name='homepage'),
    path('app1/', include('app1.urls')),
    path('app2/', include('app2.urls')),
    path('news/', include('news.urls')),
    path('libreria/', include('libreria.urls')),
    path('form/', include('forms_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

app1/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def homepage(request):
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    context={"numVisits":num_visits}
    return render(request, "homepage.html",context) 

def menu(request):
    return render(request, "menu.html")

def chi_siamo(request):
    return render(request, "chi_siamo.html")
    
def variabili(request):
    context= { 'var1': '10','var2': 'ciao', 'var3' : '123 hello world'}
    return render(request, "variabili.html",context)

def index(request):
    return render(request, "index.html")
    

app1/templates/chi_siamo.html
{% extends 'base.html'%}

{% block title %}
Chi Siamo
{% endblock title %}


{%block content%}

<h3>Bho</h3>

{%endblock content%}

app1/templates/homepage.html
{% extends 'base.html'%}

{% block title %}
Home
{% endblock title %}


{%block content%}

<h1>Ciaone Homepage</h1>
<h2>Numero visite: {{numVisits}} </h2>

<ol>
    <li><a href="{% url 'menu'%}">menu</a></li>
    <li><a href="{% url 'chi_siamo'%}">chi siamo</a></li>
    <li><a href="{% url 'variabili'%}">variabili</a></li>
    <li><a href="{% url 'app2:if'%}">if</a></li>
    <li><a href="{% url 'app2:else'%}">else</a></li>
    <li><a href="{% url 'app2:elif'%}">elif</a></li>
    <li><a href="{% url 'app2:for'%}">for</a></li>
</ol>
{%endblock content%}

app1/templates/menu.html
{% extends 'base.html'%}

{% block title %}
Menu
{% endblock title %}


{%block content%}

<ol>
    <li>Prima opzione</li>
    <li>Seconda opzione</li>
    <li>Terza opzione</li>
</ol>

{%endblock content%}

app1/templates/variabili.html
{% extends 'base.html'%}

{% block title %}
Variabili
{% endblock title %}


{%block content%}
<ol>
    <li> {{ var1 }}</li>
    <li> {{ var2 }}</li>
    <li> {{ var3 }}</li>
</ol>
{%endblock content%}