app1/urls.py
from django.urls import path
from .views import homepage, menu, chi_siamo, variabili, index

urlpatterns = [
    path('welcome/', homepage, name='home'),
    path('menu/', menu, name='menu'),
    path('chi_siamo/', chi_siamo, name='chi_siamo'),
    path('variabili/', variabili, name='variabili'),
    path('index/', index, name='index'),

]

forms_app/urls.py
from django.urls import path
from .views import contatti,registrazioneView
app_name='forms_app'

urlpatterns = [
    path('contattaci/', contatti , name="contatti"),
    path('registrazione/', registrazioneView , name="registration_view"),

]

progetto1/urls.py
from django.contrib import admin
from django.urls import path, include
from app1.views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',homepage,name='homepage'),
    path('app1/', include('app1.urls')),
    path('app2/', include('app2.urls')),
    path('news/', include('news.urls')),
    path('libreria/', include('libreria.urls')),
    path('form/', include('forms_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

templates/base.html
{%load static%}
<!doctype html>
<html lang="en">

<head>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  <style>
    .btn.btn-success {
      color: #ffffff;
      background-color: #8a458f;
      border-color: #8a458f;
    }

    .btn.btn-success:hover {
      color: #ffffff;
      background-color: #703874;
      border-color: #69346d;
    }

    .btn.btn-success:focus,
    .btn.btn-success.focus {
      box-shadow: 0 0 0 0.2rem rgba(112, 56, 116, 0.5);
    }

    .btn.btn-success.disabled,
    .btn.btn-success:disabled {
      color: #ffffff;
      background-color: #8a458f;
      border-color: #8a458f;
    }

    .btn.btn-success:not(:disabled):not(.disabled):active,
    .btn.btn-success:not(:disabled):not(.disabled).active {
      color: #ffffff;
      background-color: #69346d;
      border-color: #613064;
    }

    .show>.btn.btn-success.dropdown-toggle {
      color: #ffffff;
      background-color: #69346d;
      border-color: #613064;
    }

    .show>.btn.btn-success.dropdown-toggle:focus {
      box-shadow: 0 0 0 0.2rem rgba(112, 56, 116, 0.5);
    }

    .btn.btn-success:not(:disabled):not(.disabled):active:focus,
    .btn.btn-success:not(:disabled):not(.disabled).active:focus {
      box-shadow: 0 0 0 0.2rem rgba(112, 56, 116, 0.5);
    }



    .navbar {
      background-color: #8a458f;
    }

    .navbar .navbar-brand {
      color: #ecf0f1;
    }

    .navbar .navbar-brand:hover,
    .navbar .navbar-brand:focus {
      color: #ecdbff;
    }

    .navbar .navbar-text {
      color: #ecf0f1;
    }

    .navbar .navbar-text a {
      color: #ecdbff;
    }

    .navbar .navbar-text a:hover,
    .navbar .navbar-text a:focus {
      color: #ecdbff;
    }

    .navbar .navbar-nav .nav-link {
      color: #ecf0f1;
      border-radius: .25rem;
      margin: 0 0.25em;
    }

    .navbar .navbar-nav .nav-link:not(.disabled):hover,
    .navbar .navbar-nav .nav-link:not(.disabled):focus {
      color: #ecdbff;
    }

    .navbar .navbar-nav .dropdown-menu {
      background-color: #8a458f;
      border-color: #703874;
    }

    .navbar .navbar-nav .dropdown-menu .dropdown-item {
      color: #ecf0f1;
    }

    .navbar .navbar-nav .dropdown-menu .dropdown-item:hover,
    .navbar .navbar-nav .dropdown-menu .dropdown-item:focus,
    .navbar .navbar-nav .dropdown-menu .dropdown-item.active {
      color: #ecdbff;
      background-color: #703874;
    }

    .navbar .navbar-nav .dropdown-menu .dropdown-divider {
      border-top-color: #703874;
    }

    .navbar .navbar-nav .nav-item.active .nav-link,
    .navbar .navbar-nav .nav-item.active .nav-link:hover,
    .navbar .navbar-nav .nav-item.active .nav-link:focus,
    .navbar .navbar-nav .nav-item.show .nav-link,
    .navbar .navbar-nav .nav-item.show .nav-link:hover,
    .navbar .navbar-nav .nav-item.show .nav-link:focus {
      color: #ecdbff;
      background-color: #703874;
    }

    .navbar .navbar-toggler {
      border-color: #703874;
    }

    .navbar .navbar-toggler:hover,
    .navbar .navbar-toggler:focus {
      background-color: #703874;
    }

    .navbar .navbar-toggler .navbar-toggler-icon {
      color: #ecf0f1;
    }

    .navbar .navbar-collapse,
    .navbar .navbar-form {
      border-color: #ecf0f1;
    }

    .navbar .navbar-link {
      color: #ecf0f1;
    }

    .navbar .navbar-link:hover {
      color: #ecdbff;
    }

    @media (max-width: 575px) {
      .navbar-expand-sm .navbar-nav .show .dropdown-menu .dropdown-item {
        color: #ecf0f1;
      }

      .navbar-expand-sm .navbar-nav .show .dropdown-menu .dropdown-item:hover,
      .navbar-expand-sm .navbar-nav .show .dropdown-menu .dropdown-item:focus {
        color: #ecdbff;
      }

      .navbar-expand-sm .navbar-nav .show .dropdown-menu .dropdown-item.active {
        color: #ecdbff;
        background-color: #703874;
      }
    }

    @media (max-width: 767px) {
      .navbar-expand-md .navbar-nav .show .dropdown-menu .dropdown-item {
        color: #ecf0f1;
      }

      .navbar-expand-md .navbar-nav .show .dropdown-menu .dropdown-item:hover,
      .navbar-expand-md .navbar-nav .show .dropdown-menu .dropdown-item:focus {
        color: #ecdbff;
      }

      .navbar-expand-md .navbar-nav .show .dropdown-menu .dropdown-item.active {
        color: #ecdbff;
        background-color: #703874;
      }
    }

    @media (max-width: 991px) {
      .navbar-expand-lg .navbar-nav .show .dropdown-menu .dropdown-item {
        color: #ecf0f1;
      }

      .navbar-expand-lg .navbar-nav .show .dropdown-menu .dropdown-item:hover,
      .navbar-expand-lg .navbar-nav .show .dropdown-menu .dropdown-item:focus {
        color: #ecdbff;
      }

      .navbar-expand-lg .navbar-nav .show .dropdown-menu .dropdown-item.active {
        color: #ecdbff;
        background-color: #703874;
      }
    }

    @media (max-width: 1199px) {
      .navbar-expand-xl .navbar-nav .show .dropdown-menu .dropdown-item {
        color: #ecf0f1;
      }

      .navbar-expand-xl .navbar-nav .show .dropdown-menu .dropdown-item:hover,
      .navbar-expand-xl .navbar-nav .show .dropdown-menu .dropdown-item:focus {
        color: #ecdbff;
      }

      .navbar-expand-xl .navbar-nav .show .dropdown-menu .dropdown-item.active {
        color: #ecdbff;
        background-color: #703874;
      }
    }

    .navbar-expand .navbar-nav .show .dropdown-menu .dropdown-item {
      color: #ecf0f1;
    }

    .navbar-expand .navbar-nav .show .dropdown-menu .dropdown-item:hover,
    .navbar-expand .navbar-nav .show .dropdown-menu .dropdown-item:focus {
      color: #ecdbff;
    }

    .navbar-expand .navbar-nav .show .dropdown-menu .dropdown-item.active {
      color: #ecdbff;
      background-color: #703874;
    }
  </style>

  <title>
    {% block title %}
    My project
    {% endblock title %}
  </title>
</head>

<body>

  {% block navbar %}
  <nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="/">Progetto 1</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Prima
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/app1/menu/">Menu</a>
            <a class="dropdown-item" href="/app1/welcome/">Home</a>
            <a class="dropdown-item" href="/app1/chi_siamo/">Chi siamo</a>
            <a class="dropdown-item" href="/app1/variabili/">Variabili</a>

          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Seconda
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/app2/if/">if</a>
            <a class="dropdown-item" href="/app2/ifelse/">ifelse</a>
            <a class="dropdown-item" href="/app2/ifelif/">elif</a>
            <a class="dropdown-item" href="/app2/for/">for</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            News
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/news">homepage</a>
            <a class="dropdown-item" href="/news/lista_articoli">articoli</a>
            <a class="dropdown-item" href="/news/lista_giornalisti">giornalisti</a>

          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Libreria
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/libreria/lista_libri">libri</a>
            <a class="dropdown-item" href="/libreria/lista_autori">autori</a>

          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Contattaci
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/form/contattaci/">Contatti</a>
            

          </div>
        </li>

        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ request.user.username }}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout'%}">Esci</a>
          </div>
        </li>
       
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'forms_app:registration_view'%}">Registrati</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login'%}">Login</a>
      </li>
      
      {% endif %} 
        



      </ul>

    </div>
  </nav>
  {% endblock navbar %}




  <div class="container">
    {%block content%}



    {%endblock content%}
  </div>



  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>

  <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
</body>

</html>